🔀 :: gray color 적용
GSM-MSG/GUI-iOS pull request #41
Opened 2023-01-13 12:57 UTC by minaje0917

## 💡 개요
Gray 컬러를 추가했습니다.
## 📃 작업내용
- color에 gray 컬러 추가
- DesignSystemAsset에 gray 컬러 추가
## 🔀 변경사항

## 🙋‍♂️ 질문사항

## 🍴 사용방법

## 🎸 기타

2023-01-13 12:59 UTC, baekteun commented on Projects/Core/DesignSystem/Sources/Color/GUIColorSystem+System.swift
> +        case g120
지워주세요

2023-01-13 13:41 UTC, minaje0917 commented on Projects/Core/DesignSystem/Sources/Color/GUIColorSystem+System.swift
> +        case g120
넵

2023-01-13 13:41 UTC, baekteun requested changes
GUIColorSystem enum에 gray 추가해주세요

2023-01-13 13:48 UTC, baekteun approved these changes

2023-01-13 14:06 UTC, pasin7793 approved these changes

2023-01-14 02:32 UTC, kimsh153 approved these changes

2023-01-14 13:48 UTC, merged